### ISSUE TITLE
voice

### ISSUE THREAD

**Issue by ghostMan-sniper** [akramhussein/Mute#1]
If the voice is transferred to the maximum, can hear the noise, can solve this problem?

**Comment by akramhussein** [comment]
Hi @ghostMan-sniper 

An audio file with some level of amplitude must be played for the system to detect if its muted or not. I didn't have the tools to generate a proper audio file, but if you can find a tool and make a quick audio clip (0.5s for example) that has a very low but noticeable amplitude you can probably make it less obvious. I would suggest trying a few.

Hope that makes sense.

Thanks
Akram

**Comment by ghostMan-sniper** [comment]
thanks
