### ISSUE TITLE
Check interval lower than 0.5s

### ISSUE THREAD

**Issue by krystiansliwa** [akramhussein/Mute#11]
Hey, 
why there is lower limit for check interval? I see that sound have 100ms duration so I supose min time to check should be ~ 0.2s.

**Comment by akramhussein** [comment]
Hi @krystiansliwa - thanks for raising this, I will take a look. I suspect when the new file was added it should have been updated but was not.

**Comment by akramhussein** [comment]
Hi - I suspect it was based on the previous file but can't recall. Will need to take a look.

**Comment by krystiansliwa** [comment]
Also I tweak a bit your implementation and I changed way of time measure. I am using `CACurrentMediaTime()` which is more accurate

**Comment by krystiansliwa** [comment]
Also I noticed one weird behaviour:

- I have `AVPlayer` and `AudioSession` is configured to use `playback` category. 
- Mute is listening with `alwaysNotify` set to `false`
- My phone is in silent mode so I have `isMute = true`

Sometimes when I start playing video using AVPlayer `Mute` callback is called immediately with `false` and then with `true` which is weird. 
Did you experience sth similar?

**Comment by akramhussein** [comment]
I've never used `Mute` with that use case so unfortunately can't say I have.

Regarding the minimum check interval, if you want to create a pull request I'd be happy to take a look.
