### ISSUE TITLE
It is not working at the first start

### ISSUE THREAD

**Issue by aiyub007** [akramhussein/Mute#15]
Hi @akramhussein 

When i set this up and run the app it doesn't work 

If i go to background and then come to foreground it works as expected.

Please share solution if you have any idea.

Thanks in advance.

**Comment by aiyub007** [comment]
For more info I have camera view

**Comment by akramhussein** [comment]
Hi @aiyub007 - sorry, not sure what the issue is here. It's possible it broke in a certain version of iOS but hard to know without thorough testing. If you want to take a look I'd be happy to take a look at a pull request but unfortunately don't have time to debug it sorry.
