### ISSUE TITLE
Mute doesn't seem to be compatible for use while video recording. Is this true? Is there a workaround?

### ISSUE THREAD

**Issue by lexnasser** [akramhussein/Mute#7]
When recording video via AVFoundation, it seems that Mute does not work. Is this an error on my side or in general, and is there a fix?

**Comment by akramhussein** [comment]
Never tried it with that use-case, so can't really comment. My main use was to use it just before starting some event like before playing audio. If you find a solution to fix during video recording, happy to merge in the PR.
